name: strategia_advizo_flutter_app
description: A cross-platform AI-based hiring platform built with Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.14.0
  firebase_auth: ^4.7.0
  cloud_firestore: ^4.9.0
  provider: ^6.1.0
  http: ^1.1.0
  flutter_stripe: ^9.5.0
  file_picker: ^6.1.1
  pdf: ^3.10.0
  flutter_dotenv: ^5.1.0

flutter:
  uses-material-design: true
